server:
  port: 8087
spring:
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    enabled: true
    encoding: utf-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
  resources:
    static-locations: classpath:/static/
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /pages/
      suffix: .html

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    password: 123456
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/bpo2?serverTimezone=GMT
mybatis:
  configuration:
    map-underscore-to-camel-case: true #数据库表中的下划线自动转换为驼峰
  mapper-locations: classpath:mybatis/mapper/**/*.xml
